version: "3"
services: 
    postgres:
      image: postgres:9.5-alpine
      ports:
      - "5432:5432"
      environment:
      - "POSTGRES_PASSWORD:dalong"
    aceql-http:
      build: ./
      volumes: 
      - "./flame:/app/arthas-output"
      ports:
      - "9090:9090"